export default interface IResults {
  alamb: number,
  alfac: number,
   eu: number,
   qlim: number,
   serviceBendingMoment: number,
   fck: number,
   fyk: number,
   E: number,
   fcd: number,
   tcd: number,
   fyd: number,
   amd: number,
   delta: number,
   amilim: number,
   ami: number,
   asl: number,
   aas: number,
   a: number,
   romin: number,
   asmin: number,
   ast: number
} 